# LambdaControls configuration.

# The controls mode. Available modes: default, controller, touchscreen
controls = "default"

[hud]
    # Dertermines where the movements buttons are.
    side = "left"

# Controller settings
[controller]
    # Controller to use.
    id = 0
    # Controller's dead zone.
    dead_zone = 0.20
    # Rotation speed for look directions.
    rotation_speed = 40.0
    # Mouse speed in GUI.
    mouse_speed = 30.0
    # Controller controls
    [controller.controls]
        attack = "button_7"
        b = "button_1"
        back = "axe_1+"
        dpad_up = "button_13"
        dpad_right = "button_14"
        dpad_down = "button_15"
        dpad_left = "button_16"
        forward = "axe_1-"
        hotbar_left = "button_4"
        hotbar_right = "button_5"
        inventory = "button_3"
        jump = "button_0"
        left = "axe_0-"
        right = "axe_0+"
        sneak = "button_12"
        sprint = "button_11"
        start = "button_9"
        use = "button_6"
        view_down = "axe_3+"
        view_left = "axe_2-"
        view_right = "axe_2+"
        view_up = "axe_3-"
        x = "button_2"

# Colors
[colors]
normal = "#ffffffff"
pressed = "#ffa000ff"
background_normal = "#000000aa"
background_pressed = "#555555aa"
