# LambdaControls configuration.

# The controls mode. Available modes: default, controller, touchscreen
controls = "default"

[hud]
    # Dertermines where the movements buttons are.
    side = "left"

# Controller settings
[controller]
    dead_zone = 0.25
    rotation_speed = 25.0
    # Controller controls
    [controller.controls]
        attack = "button_7"
        back = "axe_1+"
        drop = "button_2"
        forward = "axe_1-"
        hotbar_left = "button_4"
        hotbar_right = "button_5"
        inventory = "button_3"
        jump = "button_0"
        left = "axe_0-"
        right = "axe_0+"
        sneak = "button_12"
        sprint = "button_11"
        start = "button_9"
        use = "button_6"
        view_down = "axe_3+"
        view_left = "axe_2-"
        view_right = "axe_2+"
        view_up = "axe_3-"

# Colors
[colors]
normal = "#ffffffff"
pressed = "#ffa000ff"
background_normal = "#000000aa"
background_pressed = "#555555aa"
