# LambdaControls configuration.

# The controls mode. Available modes: default, controller, touchscreen
controls = "default"

[hud]
    # Enables the HUD.
    enable = true
    # Dertermines where the movements buttons are.
    side = "left"

# Controller settings
[controller]
    # Controller to use.
    id = 0
    # Controller's type.
    type = "default"
    # Controller's dead zone.
    dead_zone = 0.20
    # Rotation speed for look directions.
    rotation_speed = 40.0
    # Mouse speed in GUI.
    mouse_speed = 30.0
    # Inverts the right X axis.
    invert_right_x_axis = false
    # Inverts the right Y axis.
    invert_right_y_axis = false
